theme = "hugo-material-docs"
metadataformat = "yaml"
canonifyurls = true
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true
# Enable Google Analytics by entering your tracking id
googleAnalytics = ""
publishDir ="docs"

[languages]
  [languages.en]
		contentDir = "content/English"
  	languageCode = "en-us"
    baseURL = "https://learn.eoscostarica.io/en/"
    languageName = "English"
    title = "EOSIO Learning Resources by EOS Costa Rica"
    weight = 1
    [languages.en.params]
	    # General information
		author = "eoscostarica"
		description = "A curated list of EOS learning resources."
		copyright = "Released under the MIT license"



  [languages.es]
		contentDir = "content/Spanish"
  	languageCode = "es-cr"
    baseURL = "https://learn.eoscostarica.io/es/"
    languageName = "Espa침ol"
    title = "Recursos para aprender EOSIO en Espa침ol por EOS Costa Rica"
    weight = 2
    [languages.es.params]
	    # Informaci칩n General
		author = "eoscostarica"
		description = "Una lista curada de recursos de aprendizaje de EOS."
		copyright = "Publicado bajo la licencia MIT"



[params]
	# Repository
	provider = "GitHub"
	repo_url = "https://github.com/eoscostarica/eos-learning-resources"

	version = "1.0.0"
	logo = "images/logo.png"
	favicon = "images/favicon.ico"

	permalink = "#"

	# Custom assets
	custom_css = []
	custom_js  = []

	# Syntax highlighting theme
	highlight_css  = ""

	[params.palette]
    	primary = "blue-grey"
    	accent  = "blue-grey"

  [params.font]
    	text = "Ubuntu"
    	code = "Ubuntu Mono"

[social]
	twitter = "eoscostarica"
	github  = "eoscostarica"
	email   = "bp@eosio.cr"

## ENGLISH MENU
[[languages.en.menu.main]]
	name   = "Blockchain Basics"
	url    = "/"
	weight = 0
[[languages.en.menu.main]]
	name   = "EOSIO Software"
	url    = "eosio-software/"
	weight = 1
[[languages.en.menu.main]]
	name   = "EOS Blockchain"
	url    = "eos-blockchain/"
	weight = 2
[[languages.en.menu.main]]
	name   = "Block Producers"
	url    = "block-producer/"
	weight = 3
[[languages.en.menu.main]]
	name   = "Block Explorers"
	url    = "block-explorers/"
	weight = 4
[[languages.en.menu.main]]
	name   = "DApp Development"
	url    = "dapp-development/"
	weight = 5
[[languages.en.menu.main]]
	name   = "EOSIO Sister Chains"
	url    = "eosio-sister-chains/"
	weight = 6
[[languages.en.menu.main]]
	name   = "DevOps"
	url    = "devops/"
	weight = 7
[[languages.en.menu.main]]
	name   = "EOS Podcasts"
	url    = "eos-podcasts/"
	weight = 8
[[languages.en.menu.main]]
	name   = "Modern C++"
	url    = "modern-cpp/"
	weight = 9

#SPANISH MENU
[[languages.es.menu.main]]
	name   = "Conceptos b치sicos de Blockchain"
	url    = "/"
	weight = 0
[[languages.es.menu.main]]
	name   = "Software EOSIO"
	url    = "eosio-software/"
	weight = 1
[[languages.es.menu.main]]
	name   = "Blockchain de EOS"
	url    = "eos-blockchain/"
	weight = 2
[[languages.es.menu.main]]
	name   = "Productores de Bloques"
	url    = "block-producer/"
	weight = 3
[[languages.es.menu.main]]
	name   = "Exploradores de Bloques"
	url    = "block-explorers/"
	weight = 4
[[languages.es.menu.main]]
	name   = "Desarrollo de DApps"
	url    = "dapp-development/"
	weight = 5
[[languages.es.menu.main]]
	name   = "Cadenas hermanas de EOSIO"
	url    = "eosio-sister-chains/"
	weight = 6
[[languages.es.menu.main]]
	name   = "DevOps"
	url    = "devops/"
	weight = 7
[[languages.es.menu.main]]
	name   = "Podcasts de EOS"
	url    = "eos-podcasts/"
	weight = 8
[[languages.es.menu.main]]
	name   = "C++ moderno"
	url    = "modern-cpp/"
	weight = 9

[blackfriday]
	smartypants	= true
	fractions = true
	smartDashes = true
	plainIDAnchors = true
